- build.gradle
- src/main/java/codesquad/issuetracker/comment/Comment.java
- src/main/java/codesquad/issuetracker/issue/Issue.java
- src/main/java/codesquad/issuetracker/label/Label.java
- src/main/java/codesquad/issuetracker/milestone/Milestone.java
- src/main/java/codesquad/issuetracker/user/User.java
<br/>
- 엔티티 클래스 작성
- `User`, `Issue`, `Label`, `Milestone`
<br/>
<br/>
> [BE] 엔티티 클래스 작성

- .github/workflows/dev.yaml
- BE/issue-tracker/Dockerfile
- BE/issue-tracker/README.md
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
- BE/issue-tracker/src/main/resources/sql/schema/schema.sql
- README.md
<br/>
- Github actions를 이용해서 스프링 및 도커 빌드를 자동화 했습니다.
- 빌드 후에 docker repository에 push해서 ec2에서 자동으로 pull하도록 했습니다.
- docker-compose를 이용해서 spring과 mysql를 함께 배포합니다.
- 배포에 필요한 중요 정보는 github secret을 이용했습니다.
- READEM 초안을 작성했습니다.
<br/>
<br/>
> [BE] Github actions와 도커를 이용한 CI/CD 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/Comment.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentCreateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ResourceNotFoundException.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Assignee.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueAttachedLabel.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/LabelRef.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/User.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserResponse.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/user/UserRepositoryTest.java
🔘Part
BE
🔎 작업 내용
- 이슈 삭제 기능 구현
- 연관된 댓글도 삭제
- Issue가 연관있는 레이블의 아이디를 참조하는 기능 구현
- 이슈 생성 기능 구현
- 이슈 상세 정보 조회 기능 구현
> [BE] 이슈 관련 기능 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/resources/sql/schema/schema.sql
<br/>
- 마일스톤 및 이슈 서비스의 순환 의존선 문제 해결
- sql 스키마 업데이트
<br/>
<br/>
> [BE] 마일스톤 및 이슈의 순환 의존성 문제 해결

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
<br/>
- 이슈 조회 시 `isDelete = true` 인 이슈는 조회하지 않도록 변경
- 열림, 닫힘 상태를 `boolean` `isOpen` 에서 `enum State` `state`로 변경
<br/>
<br/>
> [BE] 이슈 Soft Delete 기능 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ResourceNotFoundException.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
<br/>
- GlobalExceptionHandler 정의
- 존재하지 않는 데이터 조회 시 NoSuchElementException을 던지도록 변경
<br/>
<br/>
> [BE] 전역 예외 핸들러 구현

- fe/package-lock.json
- fe/package.json
- fe/src/App.tsx
- fe/src/common/APIUtils.ts
- fe/src/common/FilterUI.tsx
- fe/src/common/NotFound.tsx
- fe/src/common/Sidebar.tsx
- fe/src/common/Uploader.tsx
- fe/src/components/IssueContainer/FeedNav.tsx
- fe/src/components/IssueContainer/IssueCard.tsx
- fe/src/components/IssueContainer/IssueFeed.tsx
- fe/src/components/IssueContainer/Nav.tsx
- fe/src/components/LabelsMilestones/Labels/LabelCard.tsx
- fe/src/components/LabelsMilestones/Labels/LabelEditUI.tsx
- fe/src/components/LabelsMilestones/Labels/LabelFeed.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneCard.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneEditUI.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneFeed.tsx
- fe/src/index.css
- fe/src/main.tsx
- fe/src/pages/IssuesPage.tsx
- fe/src/pages/LabelsPage.tsx
- fe/src/pages/MilestonesPage.tsx
- fe/src/pages/NewPage.tsx
- fe/tailwind.config.js
- get, post, delete, patch, put  fetch요청 기능 추가 
- 위의 기능으로 CRUD 구현 완료 
- 레이블 텍스트 색 선택 드롭다운 기능 추가 
- 어두운색, 밝은색으로 텍스트 color black, white 적용
> ✨[FE] feat: 마일스톤 페이지 서버 데이터 적용

- fe/package-lock.json
- fe/package.json
- fe/src/common/FileUploader.tsx
- fe/src/common/FilterUI.tsx
- fe/src/common/Utils.ts
- fe/src/components/IssueContainer/IssueCard.tsx
- fe/src/components/IssueDetail/CommentArea.tsx
- fe/src/components/IssueDetail/CommentCard.tsx
- fe/src/components/IssueDetail/TitleInfo.tsx
- fe/src/components/LabelsMilestones/Labels/LabelCard.tsx
- fe/src/components/LabelsMilestones/Labels/LabelEditUI.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneCard.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneEditUI.tsx
- fe/src/components/NewIssue/NewIssue.tsx
- fe/src/pages/IssueDetail.tsx
- fe/src/pages/IssuesPage.tsx
- fe/src/pages/LabelsPage.tsx
- fe/src/pages/MilestonesPage.tsx
- 이미지 파일 업로드 시 이미지 저장 주소를 가저오도록 수정
- ReactMarkdown, remarkGfm 적용
- 이미지 url 이 포함된 텍스트를 그릴때 markdown 형식으로 변경
- 헬퍼 함수 분리
- 생성 날짜 계산 함수 추가
> ✨ feat: 파일 업로드 및 ReactMardown 적용

- BE/issue-tracker/src/main/java/codesquad/issuetracker/aop/HttpAspect.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepositoryImpl.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/utils/FieldnameConverter.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelControllerTest.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelRepositoryTest.java
<br/>
- 라벨 crud기능 구현
<br/>
<br/>
> [BE] 라벨 CRUD기능 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepositoryImpl.java
- BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelServiceTest.java
fix/label-fetch -> dev
- 삭제된 라벨이 불러와진 문제 해결
> [BE] 삭제된 라벨이 불러와진 문제 해결

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/SimpleMilestoneResponse.java
feature/issue -> dev-be
- Issue 상세 정보 DTO에 Milestone 정보를 추가
- 메서드 분리를 통해 Issue를 DTO로 변환하는 로직을 리팩토링
> [BE] 이슈 상세 페이지에 마일스톤 정보 추가

- fe/src/App.tsx
- fe/src/common/CommentBox.tsx
- fe/src/common/FilterUI.tsx
- fe/src/common/NotFound.tsx
- fe/src/common/Progressbar.tsx
- fe/src/common/Sidebar.tsx
- fe/src/common/Utils.ts
- fe/src/components/IssueContainer/FeedNav.tsx
- fe/src/components/IssueContainer/IssueFeed.tsx
- fe/src/components/IssueContainer/IssueStatusFilter.tsx
- fe/src/components/IssueDetail/CommentArea.tsx
- fe/src/components/IssueDetail/TitleContainer.tsx
- fe/src/components/IssueDetail/TitleInfo.tsx
- fe/src/components/IssueDetail/TitleView.tsx
- fe/src/components/LabelsMilestones/Labels/LabelEditUI.tsx
- fe/src/components/LabelsMilestones/Milestones/MilestoneEditUI.tsx
- fe/src/components/LabelsMilestones/Nav.tsx
- fe/src/components/NewIssue/NewIssue.tsx
- fe/src/pages/IssueDetail.tsx
- fe/src/pages/IssuesPage.tsx
- fe/src/pages/LabelsPage.tsx
- fe/src/pages/LoginPage.tsx
- fe/src/pages/MilestonesPage.tsx
- fe/src/pages/NewPage.tsx
- fe/src/pages/SignUp.tsx
ex) feature/styling -> dev-fe
- 회원가입 페이지 구현
- 레이블 API 연동(편집, 삭제, 생성)
- 이슈 상세 제목 편집 UI 구현
> ✨ feat: 페이지 스타일링

- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
- fix/milestone-duedate -> dev-be
- LocalDateTime에서 LocalDate로 타입 수정
> [BE] 마일스톤 due date의 타입 수정

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
- milestoneId가 null인 경우를 처리
ex) feature/issue-milestone -> dev-be
- Issue 생성 시 milestoneId가 null인 경우 처리
> [BE] Issue 생성 시 milestoneId가 null인 경우 처리

- fe/src/common/CommentBox.tsx
- fe/src/common/FileUploader.tsx
- fe/src/common/Modal.tsx
- fe/src/common/Utils.ts
- fe/src/components/SignUpInput/IdInput.tsx
- fe/src/components/SignUpInput/PasswordInput.tsx
- fe/src/pages/LoginPage.tsx
- fe/src/pages/SignUpPage.tsx
ex) feature/login_error -> dev-fe
- 회원가입 창에서 아이디 중복확인 클릭 기능 추가(모달로 중복 여부 알림)
- 회원가입 성공 시 "회원가입 성공" 이라는 모달을 띄우고 로그인 페이지로 이동
- 로그인 창에서 로그인을 눌렀을때 회원가입이 되어있지 않으면 경고 모달 띄우기
- 로그인 성공시 "/issue" 페이지로 이동
> ✨ feat: 로그인, 회원가입 기능 및 예외 처리

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/SimpleLabelResponse.java
fix/issue-response -> dev-be
- 이슈 목록 응답 데이터에 라벨 색을 추가 했습니다.
> [BE] 이슈 목록 응답 데이터 수정

- BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
ex) hotfix/OAuth -> dev-be
- 에러코드 오탈자 수정
- OAuth 페이지로 리다이렉트시키는 기능 버그 수정
> [BE] OAuth 리다이렉트 버그 수정

- fe/src/index.css
ex) feature/issue_detail_refactor -> dev-fe
- 스크롤바 스타일 수정
- 빌드 및 배포
> 💚 스타일 에러 수정 및 배포

- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/Comment.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentCreateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentResponse.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentUpdateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
ex) feature/update-comment -> dev-be
- 댓글 내용 수정 API 구현
> [BE] 댓글 내용 수정 기능 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
fix/create-issue -> dev
- 이슈 패키지에서 사용하지 않는 메서드 제거
- 마일스톤을 지정하지 않으면 이슈 상세 페이지를 불러오지 못하는 문제 해결
> [BE] 이슈 상세 페이지를 불러오지 못하는 문제 해결

- BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/auth/JwtTokenProvider.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/SimpleUserResponse.java
ex) feature/OAuth -> dev-be
- callback 메서드 실행 시 쿼리 스트링으로 토큰 전달
- 토큰으로 유저 정보를 반환하는 API 구현
> [BE] OAuth 로그인 기능 수정

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/AssigneeUpdateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/AttachedLabelUpdateRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/MilestoneUpdateRequest.java
ex) feature/update-issue -> dev-be
- 이슈의 레이블, 담당자, 마일스톤을 추가/제거 하는 기능 구현
> [BE] 이슈의 담당자, 레이블, 마일스톤을 추가/제거하는 기능 구현

- BE/issue-tracker/src/main/java/codesquad/issuetracker/global/repository/CrudRepositoryCustomImpl.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
hotfix/update-issue-title -> dev-be
- 이슈 제목 업데이트 오류 해결
> [BE] 이슈 제목이 업데이트 되지 않는 오류

- BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
> [BE] 이슈 생성이 안되는 오류 해결

- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepositoryCustomImpl.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
fix/milestone-duedate -> dev-be
- 마일스톤 반환타입이 LocaldateTime에서 LocalDate로 변경
> [BE]마일스톤 반환타입이 오류 수정

- BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneController.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepository.java
- BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
ex) feature/change-milestone-state -> dev-be
- 마일스톤 상태를 변경시키는 API 수정
> [BE] 마일스톤 상태를 변경시키는 API 수정
